from . import views
from django.urls import path
from django.views.decorators.csrf import csrf_exempt

urlpatterns = [
    path('validate-username/',
         csrf_exempt(views.SignUpUsernameValidationView.as_view()),
         name="validate-username"),
    path('validate-email/',
         csrf_exempt(views.SignUpEmailValidationView.as_view()),
         name='validate-email'),
    path('validate-phonenumber/',
         csrf_exempt(views.SignUpPhonenumberValidationView.as_view()),
         name="validate-phonenumber"),
    path('validate-login/',
         csrf_exempt(views.LoginEmailValidationView.as_view()),
         name="validate-login"),
    path('login/',
         views.LoginView.as_view(),
         name="LoginView"),
    path('register/',
         views.RegisterView.as_view(),
         name="RegisterView"),
    # path('datatable/',
    #      views.DataTablePageView.as_view(),
    #      name="DataTableView"),
    # path('regulartable/',
    #      views.RegularTablePageView.as_view(),
    #      name="RegularTableView"),
    # path('calculations/<pk>/',
    #      views.CalculationsPageView.as_view(),
    #      name="calculationsView"),
    path('activate/<str:user_id>/<str:token>',
         views.ActivateAccountView.as_view(),
         name='activate'),
    path('logout/',
         views.LogoutView.as_view(),
         name="LogoutView"),
]
