# Generated by Django 3.2.13 on 2022-07-13 00:25

import PrimeAccess_app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outfit_name', models.CharField(max_length=1000)),
                ('outfit_measurement_type', models.CharField(max_length=1500)),
                ('outfit_price', models.IntegerField(default=0)),
                ('record_date_edited', models.DateTimeField(auto_now=True)),
                ('record_date', models.DateTimeField(auto_now_add=True)),
                ('active_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager_data', to=settings.AUTH_USER_MODEL, verbose_name='auth_manager')),
            ],
        ),
        migrations.CreateModel(
            name='StyleImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_name', models.CharField(max_length=1000)),
                ('style_image', models.ImageField(upload_to='')),
                ('record_date_edited', models.DateTimeField(auto_now=True, null=True)),
                ('record_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransporterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transporter_name', models.CharField(max_length=1000)),
                ('record_date_edited', models.DateTimeField(auto_now=True, null=True)),
                ('record_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OutfitImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outfit_image', models.ImageField(upload_to='')),
                ('outfit_ordered', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outfit_data', to='PrimeAccess_app.inventorymodel', verbose_name='outfit_info')),
            ],
        ),
        migrations.CreateModel(
            name='OutfitColorsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=1000)),
                ('color_image', models.ImageField(upload_to=PrimeAccess_app.models.ColorPhotoRename)),
                ('record_date_edited', models.DateTimeField(auto_now=True)),
                ('record_date', models.DateTimeField(auto_now_add=True)),
                ('active_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager_color_data', to=settings.AUTH_USER_MODEL, verbose_name='auth_manager')),
            ],
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_quality', models.CharField(max_length=100)),
                ('outfit_name', models.CharField(max_length=100)),
                ('material_color', models.CharField(max_length=100)),
                ('length', models.CharField(max_length=100)),
                ('waist', models.CharField(max_length=100)),
                ('laps', models.CharField(max_length=100)),
                ('knees', models.CharField(max_length=100)),
                ('ankles', models.CharField(blank=True, max_length=100, null=True)),
                ('style_image', models.ImageField(upload_to='')),
                ('wrist_measurment', models.CharField(blank=True, max_length=100, null=True)),
                ('lower_arm_measurment', models.CharField(blank=True, max_length=100, null=True)),
                ('upper_arm_measurment', models.CharField(max_length=100)),
                ('sleeve_length_measurment', models.CharField(max_length=100)),
                ('tummy_measurment', models.CharField(max_length=100)),
                ('chest_measurment', models.CharField(max_length=100)),
                ('shoulder_measurment', models.CharField(max_length=100)),
                ('neck_measurment', models.CharField(max_length=100)),
                ('sleeve_type', models.CharField(max_length=100)),
                ('button_type', models.CharField(max_length=100)),
                ('order_remark', models.CharField(max_length=100)),
                ('order_quantity', models.IntegerField(default=0)),
                ('order_status', models.CharField(max_length=1000)),
                ('order_total_amount', models.CharField(max_length=100)),
                ('customer_name', models.CharField(max_length=1000)),
                ('customer_phone', models.CharField(help_text='Customer phone number', max_length=20)),
                ('customer_email', models.EmailField(max_length=1000)),
                ('customer_state', models.CharField(max_length=1000)),
                ('customer_address', models.CharField(max_length=1000)),
                ('deliver_date', models.DateTimeField(default=0)),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('outfit_ordered', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordered_outfit_data', to='PrimeAccess_app.inventorymodel', verbose_name='outfit_info')),
            ],
        ),
        migrations.CreateModel(
            name='DeliverySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=1500)),
                ('delivery_rate', models.IntegerField(default=0)),
                ('record_date_edited', models.DateTimeField(auto_now=True, null=True)),
                ('record_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('active_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_manager', to=settings.AUTH_USER_MODEL, verbose_name='auth_manager')),
            ],
        ),
    ]
